---
title: "Extract data from stac API"
output: html_document
date: "2025-05-13"
---
```{r}
library(rstac)
library(magrittr)
library(terra)
library(raster)
library(stars)
```

# NDVI raster
## Preparation before loading raster

A STAC URl where data catalog is located

```{r}
s_obj <- stac("https://planetarycomputer.microsoft.com/api/stac/v1/")


#Choose the location of the data (WGS) and the time
uganda_bbox <- c(29.5, -1.5, 35.0, 4.5) #
start_date <- as.Date("2022-06-01")
end_date   <- as.Date("2023-05-31")
# start_date <-as.Date("2023-07-01")
# end_date <-as.Date("2023-07-10")
```

Choose collection and load all information of all available dataset for the choosen location and time period

```{r}
it_obj <- s_obj %>%
  stac_search(
    collections = "sentinel-3-synergy-v10-l2-netcdf",
    bbox = uganda_bbox,
    datetime = paste0(as.character(start_date), "/", as.character(end_date))
  ) %>%
  get_request()
```

## Load raster in a temporary file

```{r}
signed_items <- it_obj %>% items_sign(sign_planetary_computer())
tmp_file_list = c()
for(n in 1:length(signed_items$features)){
  ndvi_url <- signed_items$features[[n]]$assets$ndvi$href
  tmp_file_list <-c(tmp_file_list, tempfile(fileext = ".nc")) 
  download.file(ndvi_url, destfile = tmp_file_list[n], mode = "wb")
}

rasters <- raster::stack(tmp_file_list)
ndvi_mean <- calc(rasters, mean, na.rm = TRUE)
plot(ndvi_mean)
```


## Crop an resize raster 

```{r}
# Define Uganda extent as an sf object
uganda_bbox_sf <- sf::st_as_sfc(sf::st_bbox(c(
  xmin = 29.5, ymin = -1.5, xmax = 35.0, ymax = 4.5
), crs = st_crs(ndvi_mean)))

# Crop the raster
ndvi_mean_uganda <- ndvi_mean %>%
  crop(extent(29.5, 35.0, -1.5, 4.5)) %>%
  as( "Raster")
 

plot(ndvi_mean_uganda)
```

## Save raster  

```{r}
writeRaster(ndvi_mean_uganda,"data/raster/ndvi_mean_uganda.tif",options=c('TFW=YES'))
```

