---
title: "4.5_spatial_autocorrelation"
output: html_document
date: "2026-03-30"
---

```{r}

covariate_standa_df <- read.table("outputs/data_for_models/covariate_standa_df.txt", stringsAsFactors = T)
Y_genus <- read.table("outputs/data_for_models/Y_genus.txt")
```

```{r}
covariate_standa_df %>%
  remove_rownames() %>%
  column_to_rownames("Sample_code") %>%
  dplyr::select(lon, lat)  -> covariate.xy
covariate.xy %>%
  as.matrix() %>%
  dist() -> sample.dist

dist(Y_genus) -> composition.dist
```

```{r}
colnames(sample.dist) == colnames(composition.dist)
rownames(sample.dist) == rownames(composition.dist)
```

```{r}
library(ade4)
library(vegan)

mantel.rtest(sample.dist, composition.dist, nrepet = 9999) -> mantel_test_results
mantel_test_results
plot(mantel_test_results)
```


```{r}
community_distance_hellinger <- vegan::vegdist(Y_genus, method = "hellinger")
community_distance_hellinger
composition.dist
mantel.rtest(sample.dist, community_distance_hellinger, nrepet = 9999) -> mantel_test_helling_results
plot(mantel_test_helling_results)
```

```{r}
genus.hel <- decostand(Y_genus, "hellinger")

genus.hel.resid <- resid(lm(as.matrix(genus.hel) ~ ., data=covariate.xy))


genus.hel.D <- dist(genus.hel.resid)

genus.correlog <- mantel.correlog(community_distance_hellinger, XY=covariate.xy, nperm=999)
summary(genus.correlog)
genus.correlog   
plot(genus.correlog)

genus.correlog2 <- mantel.correlog(community_distance_hellinger, XY=covariate.xy, cutoff=FALSE, 
   r.type="spearman", nperm=999)
summary(genus.correlog2)
genus.correlog2
plot(genus.correlog2)
```
```{r}
load(file = "outputs/models/list_mods_crossvalidation_genus_pois_log.RData")

# 1. Compute predicted values from the fitted model object 'm'
preds <- computePredictedValues(list_mods_crossvalidation[[6]]$m_converg)

# 2. Calculate the posterior mean of the predictions
preds.mean <- apply(preds, FUN = mean, MARGIN = 1)

# 3. Calculate raw residuals by subtracting predictions from observed data 'Y'
#    Note: Y must be a matrix matching the model's response structure
raw_residuals <- Y_genus - preds.mean

str(raw_residuals)

genus.res.D <- dist(raw_residuals)

genus_res.correlog <- mantel.correlog(genus.res.D, XY=covariate.xy, nperm=9999)
summary(genus_res.correlog)
genus_res.correlog   
plot(genus_res.correlog)

genus_res.correlog2 <- mantel.correlog(genus.res.D, XY=covariate.xy, cutoff=FALSE, 
   r.type="spearman", nperm=9999)
summary(genus_res.correlog2)
genus_res.correlog2
plot(genus_res.correlog2)
```

