---
title: "Untitled"
output: html_document
date: "2025-04-24"
---

```{r setup, include=FALSE}
library(tidyverse)
library(DHARMa)
library(glmmTMB)
```


```{r}
data_18S <- "data/18S_AMf_PR2/Robust_MiSeq_18S_AMf_20241120_125_samples.OTU.filtered.cleaved.nosubstringOTUs.mumu.table2"
amf_taxonomic_levels <- c("kingdom", "domain", "phylum", "class", "order", "family",
                          "genus", "species")
metadata <- read_tsv("data/metadata.txt")

amf_OTUs <- data_18S %>%
  #{{import data}}
  read_tsv() %>%
  #{{format column names}}
  rename_with(~sub("\\_.*", "", .)) %>%
  rename_with(~gsub("-", "_", .)) %>%
  rename_with(~sub("_AMF_", "", .)) %>%
  rename_with(~sub("\\_AMF.*", "", .)) %>%
  rename_with(~sub("ROB_T_", "CONT_ROB_", .)) %>%
  rename_with(~sub("ROB_Tex", "CONT_ROB_T_ex", .)) %>%
  mutate(taxonomy = str_replace_all(taxonomy, ":","_"),
       taxonomy = str_replace_all(taxonomy, "[|]","; ")) %>%
  #{{select samples from ROBUST project}}
  select(OTU, amplicon, taxonomy, starts_with("CONT", ignore.case = FALSE),
         starts_with("ROB", ignore.case = FALSE)) %>%
    #{{"Arbuscular mycorrhizal fungi & Mucoromycotina fine root endophytes" are selected}}
  filter(str_detect(taxonomy,"Glomeromycotina")|str_detect(taxonomy,"Endogonales")) %>%
  separate_wider_delim(taxonomy, names = amf_taxonomic_levels, delim = "; ", cols_remove = F) %>%
  #{{select only OTUs and controls}}
  droplevels()

taxonomy <- amf_OTUs %>%
  select(amplicon, OTU, taxonomy) %>%
  separate_wider_delim(taxonomy, names = amf_taxonomic_levels, delim = "; ", cols_remove = F)
 


d <- amf_OTUs %>% 
  replace(amf_OTUs == 0, NA) %>%
  select(amplicon, starts_with("CONT")) %>%
  pivot_longer(-amplicon, names_to = "samples", values_to = "reads") %>%
  filter(!is.na(reads))

amf_OTUs_decont <- amf_OTUs %>%
  replace(amf_OTUs == 0, NA) %>%
  pivot_longer(starts_with("ROB"), names_to = "samples", values_to = "reads") %>%
  filter(!is.na(reads)) %>%
  #{{merge with control samples}}
  left_join(count(d, amplicon, wt = reads), by = "amplicon") %>%
  #{{substract abundance of control samples}}
  mutate(reads = case_when(
    is.na(n)  ~ reads,
    n > reads ~ 0,
    TRUE      ~ reads - n)) %>%
  select(-n,-starts_with("CONT")) %>%
  pivot_wider(names_from = samples, values_from =  reads, values_fill = 0) %>%
  as_tibble() %>%
  column_to_rownames(var = "amplicon") 
```


# Rarefaction
```{r}
plot.OTUcumSums <-function(x){plot(1:length(colSums(x)), log10(sort(colSums(x))+1))}
amf_OTUs_decont %>%
  select(starts_with("ROB")) %>%
  plot.OTUcumSums
10^3.1
amf_OTUs_decont %>%
  select(starts_with("ROB"))%>%
  colSums()%>%
  sort()


amf_OTUs_decont2 <- amf_OTUs_decont %>%
  #{{sample to exclude}}
  select(starts_with("ROB"))%>%
  select(where(~ sum(.x) >= 10^3))
smallest_amf <- min(colSums(amf_OTUs_decont2))

rarefaction.func <- function(df,rar_sample, n_rare = 100, rarcur = T){
  if(rarcur){ # {{ if rarefaction curve needed}}
    df %>%
      select(starts_with("ROB")) %>%
      t() %>%
      vegan::rarecurve(step = 20, sample = rar_sample, col = "blue", cex = 0.6)
  }
  df %>%
    select(starts_with("ROB")) %>%
    dim -> D
  # {{rarefaction}}
  df_rarefy = matrix(0, nrow =  D[1], ncol = D[2])
  for(n in 1:n_rare){
    df %>%
      select(starts_with("ROB")) %>%
      t() %>%
      vegan::rrarefy(rar_sample) %>%
      t() + df_rarefy -> df_rarefy
    
  }
  round(df_rarefy/n_rare) -> df_rarefy
  df_rarefy %>%
    bind_cols(
      df %>%
        select(!starts_with("ROB"))
    ) -> df_rarefy
  rownames(df_rarefy) = rownames(df)
  return(df_rarefy)
}
amf_OTUs_decont2 %>% 
  mutate(across(starts_with("ROB"), ~as.integer(.x))) -> amf_OTUs_decont2
set.seed(2121349)
rarefaction.func(df = amf_OTUs_decont2, rar_sample = smallest_amf, rarcur = T) -> amf_OTUs_rare
amf_OTUs_rare %>%
  as.data.frame()%>%
  rownames_to_column("amplicon") %>%
  left_join(amf_OTUs_decont %>%
              rownames_to_column("amplicon") %>%
              select(-starts_with("ROB")), by ="amplicon") -> amf_OTUs_rare
```

```{r}
compute.hill.diversities<- function(community_matrix){
  div_id = c(richness = 0, shanon = 1, simpson = 2)
  
  community_matrix %>%
    dplyr::select(starts_with("ROB")) -> community_matrix
  
  div_id %>%
    purrr::map(\(x) hilldiv::hill_div(community_matrix, qvalue = x)) %>%
    as.data.frame() %>%
    rownames_to_column("soil_code") %>%
    mutate(eveness_shanon = shanon/richness,
           eveness_simson = simpson/richness) %>%
    pivot_longer(-soil_code, names_to = "hill_diversity_type", values_to = "diversity_values")
}
```


```{r}
library(readxl)
library(GGally)
library(sbm)
library(vegan)
library(FactoMineR)
soil_df <- read_xlsx("data/soil_data_dry_season_2023.xlsx") %>%
  rename(coffee_system = "Robusta coffee system", soil_code = "SAMPLE NO", sand = "Sand%", clay = "Clay%", silt = "Silt%", pH ="soil pH", 
         OC = "OC%", MO = "OM%", N = "N%", P = "P/mg/kg", K = "K/Cmol/kg", Na = "Na/Cmol/kg") %>%
  mutate(soil_code = str_c("ROB_", soil_code,"_s"))

soil_df %>%
  select(-c(soil_code, Replicate,Zone, Cluster, coffee_system, Replicate)) %>%
  decostand(method = "standardize") %>%
  ggpairs(progress = F)
soil_df %>%
  select(-c(soil_code, Replicate,Zone, Cluster, coffee_system, Replicate, OC,silt, clay)) %>%
  decostand(method = "standardize") %>%
  as.matrix()%>%
  t() %>%
  plotMyMatrix()
soil_df %>%
  select(-c(soil_code, Replicate,Zone, Cluster, coffee_system, Replicate, OC, clay)) %>%
  decostand(method = "standardize")%>%
  PCA() -> PCA_soil
PCA_soil$var$cos2/PCA_soil$var$cos2 %>% rowSums

PCA_soil$var$contrib/100
fviz_pca_biplot(PCA_soil)
```


```{r}
amf_OTUs_rare %>%
  
  compute.hill.diversities  %>%
  left_join(metadata %>% select(sampling_date,
                                altitude,
                                soil_code), by = "soil_code") %>%
  left_join(soil_df, by = "soil_code")-> diversities_afm_df

amf_OTUs_rare %>%
  
  compute.hill.diversities  %>%
  left_join(metadata %>% select(sampling_date,
                                altitude,
                                soil_code), by = "soil_code") %>%
  left_join(soil_df, by = "soil_code")-> diversities_afm_df

## Richness
diversities_afm_df %>%
  pivot_longer(c(altitude,sand,clay,silt,pH,OC,MO,N,P,K,Na)) %>%
  filter(hill_diversity_type == "richness") %>%
  ggplot() +
  geom_point(aes(value, diversity_values)) +
  geom_smooth(aes(value, diversity_values), method ="glm") +
  facet_wrap(~name, scale = "free") +
  theme_minimal()

diversities_afm_df %>%
  pivot_longer(c(sampling_date, Zone, Cluster, coffee_system)) %>%
  filter(hill_diversity_type == "richness") %>%
  ggplot() +
  geom_boxplot(aes(value, diversity_values)) +
  facet_wrap(~name, scale = "free") +
  theme_minimal()
## Shanon
diversities_afm_df %>%
  pivot_longer(c(altitude,sand,clay,silt,pH,OC,MO,N,P,K,Na)) %>%
  filter(hill_diversity_type == "shanon") %>%
  ggplot() +
  geom_point(aes(value, diversity_values)) +
  geom_smooth(aes(value, diversity_values), method ="glm") +
  facet_wrap(~name, scale = "free") +
  theme_minimal()

diversities_afm_df %>%
  pivot_longer(c(sampling_date, Zone, Cluster, coffee_system)) %>%
  filter(hill_diversity_type == "shanon") %>%
  ggplot() +
  geom_boxplot(aes(value, diversity_values)) +
  facet_wrap(~name, scale = "free") +
  theme_minimal()

#Simpson
diversities_afm_df %>%
  pivot_longer(c(altitude,sand,clay,silt,pH,OC,MO,N,P,K,Na)) %>%
  filter(hill_diversity_type == "simpson") %>%
  ggplot() +
  geom_point(aes(value, diversity_values)) +
  geom_smooth(aes(value, diversity_values), method ="glm") +
  facet_wrap(~name, scale = "free") +
  theme_minimal()

diversities_afm_df %>%
  pivot_longer(c(sampling_date, Zone, Cluster, coffee_system)) %>%
  filter(hill_diversity_type == "simpson") %>%
  ggplot() +
  geom_boxplot(aes(value, diversity_values)) +
  facet_wrap(~name, scale = "free") +
  theme_minimal()

```

```{r}
library(car)
library(MuMIn)
library(parallel)
library(modelbased)
diversities_afm_df %>%
  filter(hill_diversity_type =="richness") %>% na.omit -> richness_df

glmmTMB(formula = diversity_values~coffee_system*(MO + sand + pH + Na + P),
        data = richness_df,
        family = nbinom1,
        na.action = "na.fail") -> mod1

dredge(mod1) -> dd_select


length(attr(dd_select, "model.calls")) # n mods

subset(dd_select, delta < 5)%>%
  as.data.frame()

get.models(dd_select, 1)[[1]]
summary(get.models(dd_select, 1)[[1]])

# 5 best
lapply(get.models(dd_select, c(1,2,3,4,5)), summary) 

# best one
best_model = get.models(dd_select, 1)[[1]]
summary(best_model)

res1 <- DHARMa::simulateResiduals(best_model, plot = TRUE)
DHARMa::testOverdispersion(res1)
DHARMa::testZeroInflation(res1)
summary(best_model)
Anova(best_model)

```

```{r}
library(ggsci)
predicted <- estimate_means(best_model, c("pH","coffee_system"))
str(predicted)
predicted %>% plot
richness_df %>%
  ggplot(aes(x = pH)) +
  facet_wrap(~coffee_system)+
  geom_point(aes(y = diversity_values, color = coffee_system)) +
  geom_ribbon(data = predicted, aes(ymin = CI_low, ymax = CI_high, fill = coffee_system), alpha = 0.3) +
  geom_line(data = predicted, aes(y = Mean, color = coffee_system), linewidth = 1) +
  scale_fill_startrek() +
  scale_color_startrek() +
  labs(x = " pH", y = "Richness", fill = "Coffee system") +
   theme_classic()+
  theme(aspect.ratio = 1,
        plot.margin = margin(0, 0, 0, 0),
        axis.title.x = element_blank(),
        legend.position = "None",
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
        axis.title.y = element_text(colour = "black", size=14, face="italic"))
```

```{r}
diversities_afm_df %>%
  filter(hill_diversity_type =="shanon") %>% na.omit -> shanon_df

glmmTMB(formula = diversity_values~coffee_system*(MO + sand + pH + Na + P),
        data = shanon_df,
        family = gaussian,
        na.action = "na.fail") -> mod2

dredge(mod2) -> dd_select2


length(attr(dd_select2, "model.calls")) # n mods

subset(dd_select2, delta < 5)%>%
  as.data.frame()

get.models(dd_select2, 1)[[1]]
summary(get.models(dd_select2, 1)[[1]])

# 5 best
lapply(get.models(dd_select2, c(1,2,3,4,5)), summary) 

# best one
best_model2 = get.models(dd_select2, 1)[[1]]
summary(best_model2)

res2 <- DHARMa::simulateResiduals(best_model2, plot = TRUE)
DHARMa::testOverdispersion(res2)
DHARMa::testZeroInflation(res2)
summary(best_model2)
Anova(best_model2)

```

```{r}
diversities_afm_df %>%
  filter(hill_diversity_type == "simpson") %>% na.omit -> simpson_df
simpson_df$diversity_values %>% hist()
glmmTMB(formula = diversity_values~coffee_system*(MO + sand + pH + Na + P),
        data = richness_df,
        family = gaussian,
        na.action = "na.fail") -> mod3

dredge(mod3) -> dd_select3


length(attr(dd_select3, "model.calls")) # n mods

subset(dd_select3, delta < 5)%>%
  as.data.frame()

get.models(dd_select3, 1)[[1]]
summary(get.models(dd_select3, 1)[[1]])

# 5 best
lapply(get.models(dd_select3, c(1,2,3,4,5)), summary) 

# best one
best_model3 = get.models(dd_select3, 1)[[1]]
summary(best_model3)

res3 <- DHARMa::simulateResiduals(best_model3, plot = TRUE)
DHARMa::testOverdispersion(res3)
DHARMa::testZeroInflation(res3)
summary(best_model3)
Anova(best_model3)

```

