---
title: "Untitled"
output: html_document
date: "2025-08-07"
---
```{r include=FALSE}
library(tidyverse)
library(raster)
library(mapview)
library(leaflet)
library(leafem)
library(rasterVis)
library(readxl)
library(sf)
library(pals)

library(Hmsc)
library(ape)

```

# Spatial covariate

```{r}
covariate_df <- read.table("outputs/covariate_table.txt", stringsAsFactors = T)
```

# Abundance table

```{r}
amf_family_rare <- read.table("outputs/abundance_tables/Robust_MiSeq_18S_AMf_20241120_125_samples.OTU.filtered.cleaved.nosubstringOTUs.mumu.rarefy.family.txt", header = TRUE, stringsAsFactors = FALSE)
```


# Phylo tree at the family level

```{r echo=FALSE}
family_tree <- read.tree("outputs/phylo_tree/Robust_MiSeq_18S_AMf_20241120_125_samples_Eukaryome_Glomeromycota_family.tree")

# Inspect and root tree
family_tree$tip.label
plot(family_tree)
family_tree <- root(family_tree, "c__Archaeosporomycetes_4")

# Clean tip labels (example transformation)
family_rename <- family_tree$tip.label %>%
  str_remove("f__") %>%
  str_replace_all("[a-z]__", "Unknown ") %>%
  str_replace("_(\\d+)$", " (\\1 OTU)")

family_tree$tip.label <- family_rename
plot(family_tree)
str(family_tree)
```

```{r}

# Prepare Y matrix for families
amf_family_rare <- amf_family_rare %>%
  mutate(family = family %>%
           str_remove("f__") %>%
           str_replace_all("[a-z]__", "Unknown ") %>%
           str_replace("_(\\d+)$", " (\\1 OTU)")) %>%
  remove_rownames() %>%
  column_to_rownames("family")

Y_family <- amf_family_rare %>%
  filter(rowSums(across(starts_with("ROB")) != 0) > 3) %>%
  t()

# Prepare Y without zeros as a truncated version
Y_family_trucated <- Y_family %>%
  as.data.frame() %>%
  rownames_to_column("soil_code") %>%
  pivot_longer(-soil_code) %>%
  mutate(value = ifelse(value == 0, NA, value)) %>%
  pivot_wider(names_from = name, values_from = value) %>%
  column_to_rownames("soil_code")

# Filter tree to the families present in Y
family_tree_filter <- keep.tip(phy = family_tree, tip = colnames(Y_family))
Y_family_trucated <- Y_family_trucated[, family_tree_filter$tip.label]

# Sample names from Y
family_matrix_samples <- rownames(Y_family)
```

```{r echo=FALSE}
library(Hmsc)

nChains = 12
test.run = F
if (test.run){
  #with this option, the vignette runs fast but results are not reliable
  thin = 5
  samples = 10
  transient = 5*thin
  verbose = 5*thin
} else {
  #with this option, the vignette evaluates slow but it reproduces the results of the
  #.pdf version
  thin = 10
  samples = 500
  transient = 1000*thin
  verbose = 1000*thin
}

# Sample names from Y
family_matrix_samples <- rownames(Y_family_trucated)

Y_family_trucated %>%
  as.data.frame() %>%
  rownames_to_column("soil_code") %>%
  pivot_longer(-soil_code) %>%
  ggplot() +
  facet_wrap(~name, scales = "free") +
  geom_histogram(aes(value)) +
  labs(x = "abundances without zeros (training set)")

studyDesign <- data.frame(sample = rownames(Y_family_trucated), stringsAsFactors = TRUE)
rL <- HmscRandomLevel(units = studyDesign$sample)
```


```{r echo=FALSE}
mod_pois <- Hmsc(
  Y = Y_family_trucated,
  XData = covariate_df,
  XFormula = ~Cluster + land_degra + ndvi + precip,
  phyloTree = family_tree_filter,
  studyDesign = studyDesign,
  ranLevels = list(sample = rL),
  distr = "poisson"
)

m_converg <- sampleMcmc(
  mod_pois,
  thin = thin, samples = samples, transient = transient,
  nChains = nChains, verbose = verbose, nParallel = 12
)
save(m_converg, file = "outputs/hmsc_family_full.Rdata")
#load(file = "outputs/hmsc_family_full.Rdata")

```


```{r echo=FALSE}
# Binary presence/absence Y
Y_family_bin <- Y_family_trucated %>%
  as.data.frame() %>%
  rownames_to_column("soil_code") %>%
  pivot_longer(-soil_code) %>%
  mutate(value = ifelse(is.na(value), 0, 1)) %>%
  pivot_wider(names_from = name, values_from = value) %>%
  column_to_rownames("soil_code")

m_bin <- Hmsc(
  Y = Y_family_bin,
  XData = covariate_df,
  XFormula = ~Cluster + land_degra + ndvi + precip,
  phyloTree = family_tree_filter,
  studyDesign = studyDesign,
  ranLevels = list(sample = rL),
  distr = "probit"
)

m_converg_bin <- sampleMcmc(
  m_bin,
  thin = thin, samples = samples, transient = transient,
  nChains = nChains, verbose = verbose, nParallel = 12
)
save(m_converg2_bin, file = "outputs/hmsc_family_bin_full.Rdata")
#load(file = "outputs/hmsc_family_bin_full.Rdata")
```

```{r include=FALSE}
postBeta2 <- getPostEstimate(m_converg, parName = "Beta")
beta_results <- postBeta2$mean
mpost2 <- convertToCodaObject(m_converg)
gelman.diag(mpost2$Beta, multivariate = FALSE) -> gelman_diag_df2
gelman_diag_df2$psrf

postBeta_bin2 <- getPostEstimate(m_converg_bin, parName = "Beta")
mpost_bin2 <- convertToCodaObject(m_converg_bin)
gelman.diag(mpost_bin2$Beta, multivariate = FALSE) -> gelman_diag_bin_df2
gelman_diag_bin_df2$psrf

beta_results <- postBeta2$mean
rownames(beta_results) <- colnames(m_converg$X)
beta_results <- beta_results * ((postBeta2$support > 0.9) + (postBeta2$support < (1 - 0.9)) > 0)
beta_results <- t(beta_results)[family_tree_filter$tip.label, colnames(m_converg2$X)]
colnames(beta_results) <- c("Intercept", "Cluster B", "Cluster C", "Cluster E", "LD Medium", "LD High", "NDVI", "Rain")

```

```{r}
partition = createPartition(m_bin, nfolds = 2, column = "sample")
preds = computePredictedValues(m_bin, partition = partition) 
MF = evaluateModelFit(hM = m_bin, predY = preds)
```

```{r}
Gradient <- prepareGradient(mod_pois, XDataNew = covariate_testing)
predY <- stats::predict(m_converg, Gradient = Gradient)

Gradient2 <- prepareGradient(m_bin, XDataNew = covariate_testing)
predY2 <- stats::predict(m_converg_bin, Gradient = Gradient2)
computePredictedValues
EpredY <- predY[[1]]
EpredY2 <- predY2[[1]]

# Average over predictions
if (length(predY) > 1) {
  for (i in 2:length(predY)) {
    EpredY <- EpredY + predY[[i]]
    if (i %% 1000 == 0) print(i)
  }
  EpredY <- EpredY / length(predY)
}

if (length(predY2) > 1) {
  for (i in 2:length(predY2)) {
    EpredY2 <- EpredY2 + predY2[[i]]
    if (i %% 1000 == 0) print(i)
  }
  EpredY2 <- EpredY2 / length(predY2)
}
testing_samples
rownames(EpredY) <- covariate_testing$Sample_code
rownames(EpredY2) <- covariate_testing$Sample_code


```

```{r}
EpredY %>%
  as.data.frame() %>%
  rownames_to_column("soil_code") %>%
  pivot_longer(-soil_code, names_to = "family_names", values_to = "pred_abund") -> EpredY_long
amf_family_rare_testing %>%
  as.data.frame() %>%
  rownames_to_column("soil_code") %>%
  pivot_longer(-soil_code, names_to = "family_names", values_to = "true_abund") -> test_samples_long

EpredY_long %>%
  left_join(test_samples_long, by = join_by(family_names,soil_code)) -> abund_test_df


```

```{r}


abund_test_df %>%
  ggplot()+
  facet_wrap(~family_names, scale = "free") +
  geom_point(aes(true_abund,pred_abund)) +
  labs(x= "Observed abundances", y = "Predicted abudances")

abund_test_df %>%
  mutate(diff = true_abund - pred_abund ) %>%
  group_by(family_names) %>%
  summarise(n = n(),
    RMSE = sqrt(sum(diff**2)/n))
  
```

