---
title: "raster_formating"
output: html_document
date: "2025-05-23"
editor_options: 
  chunk_output_type: inline
---
# Packages

```{r}
library(tidyverse)
library(raster)
library(mapview)
library(leaflet)
library(raster)
```

# Load raster


```{r}
land_degradation_raster <- raster("data/raster/Uganda_ldma_2020.tif/Uganda_ldma_2020.tif")
land_degradation_raster <- ratify(land_degradation_raster)
levels(land_degradation_raster)[[1]]$land_degradation <- c("Very low", "Low", "Medium", "High", "Very High")
myPal1 <- rev(RColorBrewer::brewer.pal('PRGn', n=5))
myTheme1 <- rasterVis::rasterTheme(region = myPal1)

rasterVis::levelplot(land_degradation_raster,par.settings = myTheme1)
```


```{r}
land_cover_raster <- raster("data/raster/Uganda_Landcover_2014_Scheme_II/Uganda_Landcover_2014_Scheme_II.tif")
myPal2 <- pals::stepped2( n=18)
myTheme2 <- rasterVis::rasterTheme(region = myPal2)


rasterVis::levelplot(land_cover_raster,att ="Land_Cover", par.settings = myTheme2) 
```


```{r}
ndvi_uganda <- raster("data/raster/ndvi_mean_uganda.tif")

plot(ndvi_uganda)
```

# Annual rain
```{r}
# Define start and end
start <- as.Date("2022-06-01")
end   <- as.Date("2023-05-31")

# Sequence of months
dates <- seq(start, end, by = "month")
dates_fmt <- format(dates, "%Y-%m")

# Build file paths automatically
files <- file.path(
  "data/raster/wc2.1_cruts4.09_5m_prec_2020-2024",
  paste0("wc2.1_cruts4.09_5m_prec_", dates_fmt, ".tif")
)

# Load all rasters as a stack
rasters <- stack(files)

# Mean across time
precip_mean <- calc(rasters, mean, na.rm = TRUE)
plot(precip_mean)
```

# Annual T° max

```{r}
# Define start and end
start <- as.Date("2022-06-01")
end   <- as.Date("2023-05-31")

# Sequence of months
dates <- seq(start, end, by = "month")
dates_fmt <- format(dates, "%Y-%m")

# Build file paths automatically
files <- file.path(
  "data/raster/wc2.1_cruts4.09_5m_tmax_2020-2024",
  paste0("wc2.1_cruts4.09_5m_tmax_", dates_fmt, ".tif")
)

# Load all rasters as a stack
rasters <- stack(files)

# Mean across time
t_max_mean <- calc(rasters, mean, na.rm = TRUE)
plot(t_max_mean)
```

# Annual T° min

```{r}
# Define start and end
start <- as.Date("2022-06-01")
end   <- as.Date("2023-05-31")

# Sequence of months
dates <- seq(start, end, by = "month")
dates_fmt <- format(dates, "%Y-%m")

# Build file paths automatically
files <- file.path(
  "data/raster/wc2.1_cruts4.09_5m_tmin_2020-2024",
  paste0("wc2.1_cruts4.09_5m_tmin_", dates_fmt, ".tif")
)

# Load all rasters as a stack
rasters <- stack(files)

# Mean across time
t_min_mean <- calc(rasters, mean, na.rm = TRUE)
plot(t_min_mean)
```

```{r}
library(sf)
library(raster)
library(terra)

cluster_agro_sf <- read_sf("data/raster/Robust-Agroecological-Clusters/Robust Layers/Kmeans_Robust.shp")
v <- vect(cluster_agro_sf)
raster_template <- rast(ext(v), resolution = 0.01)
crs(raster_template) <- crs(v)
v$id <- 1:8
r_raster <- rasterize(v, raster_template, field = "id")
cluster_agro <- raster(r_raster)

myPal3 <- ggsci::pal_simpsons()(8)
myTheme3 <- rasterVis::rasterTheme(region = myPal3)
cluster_agro <- ratify(cluster_agro)
rasterVis::levelplot(cluster_agro, att = "ID", par.settings = myTheme3)

```

# Formating


```{r}

if(file.exists("outputs/raster/land_degradation_lower_res.tif")){
  land_degradation_lower_res <- raster("outputs/raster/land_degradation_lower_res.tif")
  land_degradation_reclassify <- raster("outputs/raster/land_degradation_reclassify.tif")
} else {
  land_degradation_lower_res <- raster::aggregate(land_degradation_raster, fact=50, fun = modal,  na.rm=TRUE)
  land_degradation_lower_res <- ratify(land_degradation_lower_res)
  levels(land_degradation_lower_res)[[1]]$land_degradation <- c("Very low", "Low", "Medium", "High", "Very High")
 
  rasterVis::levelplot(test,par.settings = myTheme1)
  writeRaster(land_degradation_lower_res,
            filename = "outputs/raster/land_degradation_lower_res.tif",options=c('TFW=YES'), overwrite=TRUE)
  foreign::write.dbf(levels(land_degradation_lower_res)[[1]], file = "outputs/raster/land_degradation_lower_res.tif.vat.dbf")
  
  ### Land degradation reclassify
  
  m <- matrix(c(1, 1,   # values 1 → 1
                2, 1,   # values 2 → 1
                3, 2,   # value 3 → 2
                4, 3,   # values 4 → 3
                5, 3    # values 5 → 3
                ), ncol=2, byrow=TRUE)
  
  reclassify(land_degradation_lower_res,m) -> land_degradation_reclassify
  land_degradation_reclassify <- ratify(land_degradation_reclassify)
  levels(land_degradation_reclassify)[[1]]$land_degradation <- c("Low", "Medium", "High")
  writeRaster(land_degradation_reclassify,
            filename = "outputs/raster/land_degradation_reclassify.tif",options=c('TFW=YES'), overwrite=TRUE)
  foreign::write.dbf(levels(land_degradation_reclassify)[[1]], file = "outputs/raster/land_degradation_reclassify.tif.vat.dbf")
}

rasterVis::levelplot(land_degradation_lower_res,par.settings = myTheme1)
rasterVis::levelplot(land_degradation_reclassify,par.settings = myTheme1)

if(file.exists("outputs/raster/land_cover_lower_res.tif")){
  land_cover_resampled <- raster("outputs/raster/land_cover_lower_res.tif")
} else {
  land_cover_resampled <- raster::aggregate(land_cover_raster,fact=150,fun = modal)
  land_cover_resampled <- raster::resample(land_cover_resampled,land_degradation_lower_res, method = "ngb")
  land_cover_resampled <- raster::ratify(x = land_cover_resampled)
  levels(land_cover_resampled)[[1]]$Land_Cover <- levels(land_cover_raster)[[1]]$Land_Cover
  
  writeRaster(land_degradation_lower_res,
            filename = "outputs/raster/land_degradation_lower_res.grd",
            format = "raster",
            overwrite = TRUE)
  writeRaster(land_cover_resampled,"outputs/raster/land_cover_lower_res.tif",options=c('TFW=YES'))
  foreign::write.dbf(levels(land_cover_resampled)[[1]], file = "outputs/raster/land_cover_lower_res.tif.vat.dbf")
}
rasterVis::levelplot(land_cover_resampled,par.settings = myTheme2)


if(file.exists("outputs/raster/ndvi_uganda_lower_res.tif")){
  ndvi_uganda_lower_res <- raster("outputs/raster/ndvi_uganda_lower_res.tif")
  }else{
  ndvi_uganda_lower_res <- raster::resample(ndvi_uganda, land_degradation_lower_res, method = "ngb")
  writeRaster(ndvi_uganda_lower_res,"outputs/raster/ndvi_uganda_lower_res.tif",options=c('TFW=YES'), overwrite=TRUE)
  }
plot(ndvi_uganda)

plot(ndvi_uganda_lower_res)


if(file.exists("outputs/raster/precip_2023_lower_res.tif")){
  precip_2023_lower_res <- raster("outputs/raster/precip_2023_lower_res.tif")
  }else{
  precip_2023_resampled <- raster::resample(precip_mean, land_degradation_lower_res, method = "ngb")
  precip_2023_lower_res <- mask(precip_2023_resampled, land_degradation_lower_res)
  writeRaster(precip_2023_lower_res,"outputs/raster/precip_2023_lower_res.tif",options=c('TFW=YES'), overwrite=TRUE)
  }

plot(precip_2023_lower_res)

if(file.exists("outputs/raster/tmax_2023_lower_res.tif")){
  tmax_2023_lower_res <- raster("outputs/raster/tmax_2023_lower_res.tif")
  }else{
  tmax_2023_resampled <- raster::resample(t_max_mean, land_degradation_lower_res, method = "ngb")
  tmax_2023_lower_res <- mask(tmax_2023_resampled, land_degradation_lower_res)
  writeRaster(tmax_2023_lower_res,"outputs/raster/tmax_2023_lower_res.tif",options=c('TFW=YES'), overwrite=TRUE)
  }

plot(tmax_2023_lower_res)

if(file.exists("outputs/raster/tmin_2023_lower_res.tif")){
  tmin_2023_lower_res <- raster("outputs/raster/tmin_2023_lower_res.tif")
  }else{
  tmin_2023_resampled <- raster::resample(t_min_mean, land_degradation_lower_res, method = "ngb")
  tmin_2023_lower_res <- mask(tmin_2023_resampled, land_degradation_lower_res)
  writeRaster(tmin_2023_lower_res,"outputs/raster/tmin_2023_lower_res.tif",options=c('TFW=YES'), overwrite=TRUE)
  }

plot(tmin_2023_lower_res)

if(file.exists("outputs/raster/land_cover_lower_res.tif")){
  cluster_agro_lower_res <- raster("outputs/raster/cluster_agro_lower_res.tif")
} else {
  cluster_agro_resampled <- raster::resample(cluster_agro, land_degradation_lower_res, method = "ngb")
  cluster_agro_lower_res <- mask(cluster_agro_resampled, land_degradation_lower_res)
  cluster_agro_lower_res <- raster::ratify(x = cluster_agro_lower_res)
  levels(cluster_agro_lower_res)[[1]]
  levels(cluster_agro_lower_res)[[1]]$Cluster <- c("A", "B", "C", "D", "E", "F", "G", "H")
 
  
  writeRaster(land_cover_resampled,"outputs/raster/land_cover_lower_res.tif",options=c('TFW=YES'))
  foreign::write.dbf(levels(land_cover_resampled)[[1]], file = "outputs/raster/land_cover_lower_res.tif.vat.dbf")
}
rasterVis::levelplot(cluster_agro_lower_res,par.settings = myTheme3)
```


