---
title: "Untitled"
output: html_document
date: "2025-10-01"
---

```{r include=FALSE}
library(tidyverse)
library(raster)
library(mapview)
library(leaflet)
library(leafem)
library(rasterVis)
library(readxl)
library(sf)
library(pals)
library(viridis)


main_theme = theme_minimal() +
 theme(aspect.ratio = 1,
        axis.text.x = element_text(colour = "black", size=13, face="italic",angle =45, vjust =1, hjust =1),
        axis.text.y = element_text(colour = "black", size=13, face="italic"),
        axis.title = element_text(colour = "black", size=12),
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
        legend.title = element_text(colour = "black", size=12,
                                    hjust =0.5),

        legend.text = element_text(colour = "black", size=13))

main_theme_final = theme_bw() +
 theme(aspect.ratio = 1,
        axis.text.x = element_text(colour = "black", size=7, face="italic", vjust =1, hjust =1),
        axis.text.y = element_text(colour = "black", size=7, face="italic"),
        axis.title = element_text(colour = "black", size=9),
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 0.8),
        #panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_text(colour = "black", size=9,
                                    hjust =0.5),
        legend.key.size = unit(0.3, 'cm'),
        legend.text = element_text(colour = "black", size=7,face="italic"),
        strip.background = element_blank(),
        strip.text = element_text(margin = margin(0.05,0,0.05,0, "cm"),size = 7),
        title = element_text(colour = "black", size=9))
```
# Spatial covariate

## Sampling points
```{r echo=FALSE}
metadata <- read_xlsx(path = "data/Metadata_Doreen_070525.xlsx")
# soil_metadata <- read_xlsx(path = "data/soil_data_dry_season_2023.xlsx") %>% 
#   dplyr::select(-c(Zone, Cluster, Replicate,`Robusta coffee system`)) %>%
#   rename(Sample_code = "SAMPLE NO",
#           clay = "Clay%",
#           N = "N%",
#           OC = "OC%",
#           pH = "soil pH",
#           sand= "Sand%",
#           silt = "Silt%",
#           OM = "OM%",
#           P = "P/mg/kg",
#           K = "K/Cmol/kg",
#           Na = "Na/Cmol/kg")

utm_coords <- metadata %>%
  mutate(
    zone = as.numeric(substr(easting, 1, 2)),
    band = substr(easting, 3, 3),
    easting = as.numeric(sub(".* ", "", easting)),
    northing = as.numeric(northing),

    hemisphere = ifelse(band == "N", "north", "south") # M = South Hemisphere
  )

# Function to convert a single row to lat/lon
convert_to_wgs84 <- function(zone, hemisphere, easting, northing,Sample_code) {
  epsg <- if (hemisphere == "north") {
    32600 + zone  # Northern hemisphere UTM EPSG codes
  } else {
    32700 + zone  # Southern hemisphere UTM EPSG codes
  }

  point <- st_sfc(st_point(c(easting, northing)), crs = epsg)
  point_wgs84 <- st_transform(point, crs = 4326)
  coords <- st_coordinates(point_wgs84)
  tibble( lon = coords[1], lat = coords[2],Sample_code = Sample_code)
}
utm_coords %>%
  mutate(zone = case_when(zone==32~ 36,
                             .default = zone),
          northing = case_when(Sample_code == "N17" ~ 86562,
                             .default = northing)) -> utm_coords
# Apply to each row
wgs84_coords <- pmap_dfr(utm_coords[, c("zone", "hemisphere", "easting", "northing","Sample_code")], convert_to_wgs84) %>%
  st_as_sf(coords = c("lon", "lat"),crs = 4326) %>%
  mutate(
     lon= st_coordinates(.)[,1],
     lat= st_coordinates(.)[,2]
  )


leaflet() %>% 
  addTiles() %>%
  addMarkers(data=wgs84_coords,~lon, ~lat, popup = ~paste(round(lat,2), round(lon,2)) , label = ~Sample_code)%>%
  addCircleMarkers(data = wgs84_coords, lng = ~lon,
                  lat = ~lat, radius = 8, color = "blue", fillOpacity = 0.8)
```

## NDVI

Indice for vegetation quantity
https://planetarycomputer.microsoft.com/dataset/sentinel-3-synergy-v10-l2-netcdf

```{r echo=FALSE}
ndvi_uganda <- raster("outputs/raster/ndvi_uganda_lower_res.tif")

ndvi_df <- raster::extract(ndvi_uganda, wgs84_coords)%>%
 tibble(ndvi = .,
    Sample_code  = wgs84_coords$Sample_code)

pal_ndvi <- colorNumeric("viridis", domain = c(0, 1))
leaflet() %>%
  addTiles() %>% 
  addRasterImage(ndvi_uganda, opacity = 0.7) %>%
  addLegend(
    "bottomright",
    pal = pal_ndvi,
    values = c(0, 1),
  )
```

## Precipitation and Temperature max min

This is still work in progess, here the precipitation are for only **May 2023**. It is hard to get the data but I will try to obtain mean or sum precipitation for a hole year before June 2023.

```{r echo=FALSE}
precip_uganda_resampled <- raster("outputs/raster/precip_2023_lower_res.tif")

precip_df <- raster::extract(precip_uganda_resampled, wgs84_coords)%>%
 tibble(precip = .,
    Sample_code  = wgs84_coords$Sample_code)
pal_precip <- colorNumeric("Spectral", domain = c(0, 1))
leaflet() %>%
  addTiles() %>%
  addRasterImage(precip_uganda_resampled, opacity = 0.5)%>%
    addLegend(
    "bottomright",
    pal = pal_precip,
    values = c(0, 1),
  )

```

```{r echo=FALSE}
tmax_uganda_resampled <- raster("outputs/raster/tmax_2023_lower_res.tif")

tmax_df <- raster::extract(tmax_uganda_resampled, wgs84_coords)%>%
 tibble(tmax = .,
    Sample_code  = wgs84_coords$Sample_code)
pal_t <- colorNumeric("Spectral", domain = c(0, 34))
leaflet() %>%
  addTiles() %>%
  addRasterImage(tmax_uganda_resampled, opacity = 0.5)%>%
    addLegend(
    "bottomright",
    pal = pal_t,
    values = c(0, 34),
  )

```

```{r echo=FALSE}
tmin_uganda_resampled <- raster("outputs/raster/tmin_2023_lower_res.tif")

tmin_df <- raster::extract(tmin_uganda_resampled, wgs84_coords)%>%
 tibble(tmin = .,
    Sample_code  = wgs84_coords$Sample_code)
leaflet() %>%
  addTiles() %>%
  addRasterImage(tmin_uganda_resampled, opacity = 0.5)%>%
    addLegend(
    "bottomright",
    pal = pal_t,
    values = c(0, 34),
  )

```

```{r}
delta_t_uganda <- tmax_uganda_resampled -tmin_uganda_resampled

tdelta_df <- raster::extract(delta_t_uganda, wgs84_coords)%>%
 tibble(tdelta = .,
    Sample_code  = wgs84_coords$Sample_code)
tdelta_df %>% summary()
leaflet() %>%
  addTiles() %>%
  addRasterImage(delta_t_uganda, opacity = 0.5)%>%
    addLegend(
    "bottomright",
    pal = pal_t,
    values = c(9, 12),
  )
```

```{r echo=FALSE}
wind_2023 <- raster("outputs/raster/wind_2023.tif")
pal_wind <- colorNumeric("Spectral", domain = c(0, 4))
wind_df <- raster::extract(wind_2023, wgs84_coords)%>%
 tibble(wind = .,
    Sample_code  = wgs84_coords$Sample_code)
leaflet() %>%
  addTiles() %>%
  addRasterImage(wind_2023, opacity = 0.5)%>%
    addLegend(
    "bottomright",
    pal = pal_wind,
    values = c(0, 4),
  )

```

## Merge data

```{r echo=FALSE}
wgs84_coords %>%
  left_join(ndvi_df, by = "Sample_code") %>%
  left_join(precip_df, by = "Sample_code") %>%
  left_join(tmax_df, by = "Sample_code") %>%
  left_join(tmin_df, by = "Sample_code") %>%
  left_join(tdelta_df, by ="Sample_code") %>%
  left_join(wind_df, by ="Sample_code") -> wgs84_coords

```

# Joint species distribution models at the genus level

```{r}
amf_genus_rare <- read.table("outputs/abundance_tables/Robust_MiSeq_18S_AMf_20241120_125_samples.OTU.filtered.cleaved.nosubstringOTUs.mumu.afm_rarefy_all_genus.txt", header = TRUE, stringsAsFactors = FALSE)

Y_genus <- amf_genus_rare %>%
  remove_rownames() %>%
  column_to_rownames("genus") %>%
  filter(rowSums(across(starts_with("ROB")) != 0) > 3) %>%
  t()

colSums(Y_genus)
rowSums(Y_genus)
```

```{r echo=FALSE}

genus_tree <- ape::read.tree("outputs/phylo_tree/Robust_MiSeq_18S_AMf_20241120_125_samples_Eukaryome_Glomeromycota_genus.tree")
genus_tree <- ape::keep.tip(phy = genus_tree, tip = amf_genus_rare$genus)
plot(genus_tree)
genus_tree <- ape::root(genus_tree, "g__Paraglomus_7")
plot(genus_tree)
# Clean tip labels (example transformation)
# genus_rename <- genus_tree$tip.label %>%
#   str_remove("g__") %>%
#   str_replace_all("[a-z]__", "Unknown ") %>%
#   str_replace("_(\\d+)$", " (\\1 OTU)")
# length(genus_rename)
# genus_tree$tip.label <- genus_rename
# plot(genus_tree)
# str(genus_tree)
```

```{r}
all(genus_tree$tip.label %in% colnames(Y_genus))

genus_tree_filter <- ape::keep.tip(phy = genus_tree, tip = colnames(Y_genus))

all(genus_tree_filter$tip.label %in% colnames(Y_genus))
all(colnames(Y_genus) %in% genus_tree_filter$tip.label)
```

```{r}
write.table(Y_genus, "outputs/data_for_models/Y_genus.txt")
ape::write.tree(genus_tree_filter, "outputs/data_for_models/Y_genus.tree")
```

```{r}
covariate_df <- wgs84_coords %>% 
  as.data.frame() %>%
  mutate(Sample_code = str_c("ROB_", Sample_code, "_s")) %>%
  filter(Sample_code %in% rownames(Y_genus)) %>%
  dplyr::select(-geometry) %>%
  dplyr::slice(match(rownames(Y_genus), Sample_code))

covariate_df %>%
  column_to_rownames("Sample_code") %>%
  mutate(across(where(is.numeric), ~vegan::decostand(.x, method = "standardize")[,1])) %>%
  rownames_to_column("Sample_code") %>%
  mutate(Sample_code = as.factor(Sample_code)) -> covariate_standa_df
```


```{r}
write.table(covariate_df, "outputs/data_for_models/covariate_df.txt")
write.table(covariate_standa_df, "outputs/data_for_models/covariate_standa_df.txt")
```

```{r}
# Prepare Y matrix for families
amf_genus_rare <- amf_genus_rare %>%
  mutate(genus = genus %>%
           str_remove("g__") %>%
           str_replace_all("[a-z]__", "Unknown ") %>%
           str_replace("_(\\d+)$", " (\\1 OTU)")) %>%
  remove_rownames() %>%
  column_to_rownames("genus")

Y_genus <- amf_genus_rare %>%
  filter(rowSums(across(starts_with("ROB")) != 0) > 3) %>%
  t()
rowSums(Y_genus)
# Prepare Y without zeros as a truncated version
Y_genus_trucated <- Y_genus %>%
  as.data.frame() %>%
  rownames_to_column("soil_code") %>%
  pivot_longer(-soil_code) %>%
  mutate(value = ifelse(value == 0, NA, value)) %>%
  pivot_wider(names_from = name, values_from = value) %>%
  column_to_rownames("soil_code")

# Filter tree to the families present in Y
genus_tree_filter <- keep.tip(phy = genus_tree, tip = colnames(Y_genus))
Y_genus <- Y_genus[, genus_tree_filter$tip.label]
Y_genus_trucated <- Y_genus_trucated[, genus_tree_filter$tip.label]

# Sample names from Y
genus_matrix_samples <- rownames(Y_genus)
```
