---
title: "Untitled"
output: html_document
date: "2025-08-12"
---


```{r include=FALSE}
library(tidyverse)
library(raster)
library(mapview)
library(leaflet)
library(leafem)
library(rasterVis)
library(readxl)
library(sf)
library(pals)

```


```{r echo=FALSE}
metadata <- read_xlsx(path = "data/Metadata_Doreen_070525.xlsx")

utm_coords <- metadata %>%
  mutate(
    zone = as.numeric(substr(easting, 1, 2)),
    band = substr(easting, 3, 3),
    easting = as.numeric(sub(".* ", "", easting)),
    northing = as.numeric(northing),

    hemisphere = ifelse(band == "N", "north", "south") # M = South Hemisphere
  )

# Function to convert a single row to lat/lon
convert_to_wgs84 <- function(zone, hemisphere, easting, northing,Sample_code) {
  epsg <- if (hemisphere == "north") {
    32600 + zone  # Northern hemisphere UTM EPSG codes
  } else {
    32700 + zone  # Southern hemisphere UTM EPSG codes
  }

  point <- st_sfc(st_point(c(easting, northing)), crs = epsg)
  point_wgs84 <- st_transform(point, crs = 4326)
  coords <- st_coordinates(point_wgs84)
  tibble( lon = coords[1], lat = coords[2],Sample_code = Sample_code)
}
utm_coords %>%
  mutate(zone = case_when(zone==32~ 36,
                             .default = zone),
          northing = case_when(Sample_code == "N17" ~ 86562,
                             .default = northing)) -> utm_coords
# Apply to each row
wgs84_coords <- pmap_dfr(utm_coords[, c("zone", "hemisphere", "easting", "northing","Sample_code")], convert_to_wgs84) %>%
  left_join(metadata, by = "Sample_code") %>%
  st_as_sf(coords = c("lon", "lat"),crs = 4326) %>%
  mutate(
     lon= st_coordinates(.)[,1],
     lat= st_coordinates(.)[,2]
  )


leaflet() %>% 
  addTiles() %>%
  addMarkers(data=wgs84_coords,~lon, ~lat, popup = ~paste(round(lat,2), round(lon,2)) , label = ~Sample_code)%>%
  addCircleMarkers(data = wgs84_coords, lng = ~lon,
                  lat = ~lat, radius = 8, color = "blue", fillOpacity = 0.8)
```

```{r}
clay_raster <- raster("data/raster/soil_data/clay.tif")
nitrogen_raster <- raster("data/raster/soil_data/nitrogen.tif")
OC_raster <- raster("data/raster/soil_data/organic_carbone.tif")
pH_raster <- raster("data/raster/soil_data/pH.tif")
sand_raster <- raster("data/raster/soil_data/sand.tif")
silt_raster <- raster("data/raster/soil_data/silt.tif")

soil_estimted_value_df <- tibble(`Clay%`= raster::extract(clay_raster, wgs84_coords),
                                 `N%` = raster::extract(nitrogen_raster, wgs84_coords),
                                 `OC%` = raster::extract(OC_raster, wgs84_coords),
                                 `soil pH` = raster::extract(pH_raster, wgs84_coords),
                                 `Sand%` = raster::extract(sand_raster, wgs84_coords),
                                 `Silt%` = raster::extract(silt_raster, wgs84_coords),
                                 
    Sample_code  = wgs84_coords$Sample_code) %>%
  mutate(tot = `Sand%` + `Silt%` + `Clay%`,
         `Clay%` = `Clay%`/tot*100,
         `Sand%` = `Sand%`/tot*100,
         `Silt%` = `Silt%`/tot*100,
         `N%` = `N%`/1000,
         `OC%` = `OC%`/100,
         `soil pH` = `soil pH`/10
         ) %>%
    dplyr::select(-tot) %>%
  pivot_longer(-Sample_code, values_to = "estimted_val", names_to = "varaibles")
```


```{r}
soil_data <- read_xlsx("data/soil_data_dry_season_2023.xlsx")

  
soil_data %>% 
  rename(Sample_code = "SAMPLE NO") %>%
  dplyr::select("Sand%", "Clay%","Silt%","soil pH", "OC%" , "N%", "Sample_code") %>%
  pivot_longer(-Sample_code, values_to = "observed_val", names_to = "varaibles") %>%
  left_join(soil_estimted_value_df, by = c("varaibles", "Sample_code")) %>%
  ggplot()+
  geom_point(aes(observed_val, estimted_val)) +
  geom_abline(slope =1, intercept = 0) +
  facet_wrap(~varaibles, scale = "free") +
  theme(aspect.ratio = 1)
  
```

